### ISSUE TITLE
OpenCore 相比 Clover 有什么优势吗。

### ISSUE THREAD

**Issue by zanderzhng** [fangf2018/ASRock-Z390-Phantom-ITX-OpenCore-Hackintosh#1]
Catalina 出来了，准备重新做一次系统。感觉最近关于 OC 的讨论多了很多，你这边有感受到什么特别的地方吗。

**Comment by GeekAudio** [comment]
1. OpenCore 启动黑苹果 (尤其是 macOS 10.15) 会比 Clover 快不少
2. OpenCore 提供强大的排错功能和详细的日志
3. OpenCore 更加注重系统的安全性同时对文件保险箱 (FileVault) 有更强大的支持 4. OpenCore 支持基于 boot.efi 的原生开机快捷键支持
按住 Option 或 ESC 来选择启动项
按住 Command + R 来进入恢复模式
按住 Command + Option + R + R 来重置 NVRAM
5. OpenCore 使用更加先进的方法注入内核扩展 (Kext) 且与此同时不会破坏系统完整性保护。
6. OpenCore 通过读取启动磁盘设置的 NVRAM 变量, 可以像白苹果一样支持在设置的启动磁盘切换默认引导项 7. 支持给其它 .efi 驱动或引导工具加入参数
8. 如下 .efi 驱动被合并入 OpenCore, 未来的开发直接与 OpenCore 绑定, 且不再支持 Clover
AptioMemoryFix 已经被合并入 OpenCore 并将未合并的模组更名为 FwRuntimeVariable.efi , 提供更多 可按需求定制 Slide 值计算的 Quirk
AppleGenericInput (原来的 AptioInputFix) 为了提高兼容性和 ALT / Command 键的对调即将合并入 OpenCore 并增加更多的 Quirk
AppleUiSupport 为了提供更好的 FileVault 体验, 已合并入 OpenCore 并增加了更多的 Quirk
ApfsDriverLoader 计划在未来合并苹果最新的 APFS 驱动源码并支持 Fusion Drive, 有可能并入 OpenCore 9. 从 2019 年 9 月以后, Acidanthera 开发的内核驱动 (Lilu, AppleALC 等等) 不再会在 Clover 上做兼容性测试

**Comment by zanderzhng** [comment]
@fangf2018 黑果小兵的帖子嘛，我也看的。
OC 能自动解决 USB 端口数量限制吗。
另外我和你一样的主板，在 Clover 上是注入使用的 2 * 32 的内存，这一块你有接触吗。

**Comment by yuriren** [comment]
> 
OC 能自动解决 USB 端口数量限制吗。
//不能的。需要usbmap才行

**Comment by xiaooloong** [comment]
> > 
> 
> OC 能自动解决 USB 端口数量限制吗。 //不能的。需要usbmap才行

两年半了兄dei😂

**Comment by yuriren** [comment]
> 

不好意思兄dei 没注意时间。
oc现在更新到了0.7.9，真的是稳的一笔
