### ISSUE TITLE
Kernel Panic when loading Bootloader

### ISSUE THREAD

**Issue by jwmann** [fangf2018/ASRock-Z390-Phantom-ITX-OpenCore-Hackintosh#10]
I have updated my USB's EFI with the current master of the branch (commit SHA1 edfdfdb)
As soon as I try to load the UEFI on my USB it will kernel panic.

Maybe the NVRAM is booting the wrong disk?

~~In #9 you mention that I need to update the SMBIOS Platform Generic. I have done that but it doesn't make any difference. I have also removed the patches for the RX5500 since I don't use this card.~~

Also, can you let me know if "博通网卡" directory is required?
It seems like it is just for the Airport/Bluetooth patching and I haven't switched the wifi card yet.

**Comment by jwmann** [comment]
Kernal panic throws errors something about FakeSMC being a dependency for one of it the extensions being loaded. Which is weird because we're using VirtualSMC

I also haven't choosen a boot disk at this point either.

I have another Hackintosh drive connected to the computer so perhaps the NVRAM is trying to load that one instead?

**Comment by jwmann** [comment]
I moved back to the [v0.5.2](https://github.com/fangf2018/ASRock-Z390-Phantom-ITX-OpenCore-Hackintosh/tree/v0.5.2) release and changed the SMBIOS as you suggested and it worked! I was able to choose the drive I wanted and it worked.

The current version still doesn't work however

**Comment by FKABC** [comment]
> I moved back to the [v0.5.2](https://github.com/fangf2018/ASRock-Z390-Phantom-ITX-OpenCore-Hackintosh/tree/v0.5.2) release and changed the SMBIOS as you suggested and it worked! I was able to choose the drive I wanted and it worked.
> 
> The current version still doesn't work however

Hi, I am also working on this, which product model do you choose for SMBIOS? 
Thanks!

**Comment by jwmann** [comment]
> Hi, I am also working on this, which product model do you choose for SMBIOS?
> Thanks!

I use the same as the repo,  iMac 19,1

**Comment by jwmann** [comment]
I'm using Catalina and I don't seem to be able to get the nvram thing working. Yes I've 'installed' the logout hook.

How do I know if it has worked or not?
