### ISSUE TITLE
BCM943602CS在OC引导下只能跑到10M，每次开机都要关闭再打开WIFI才能恢复正常速度

### ISSUE THREAD

**Issue by x1ongzhu** [fangf2018/ASRock-Z390-Phantom-ITX-OpenCore-Hackintosh#15]
200M宽带，BCM943602CS在OC引导下只能跑到10M，每次开机都要关闭再打开WIFI才能恢复正常速度，CLOVER下一切正常

**Comment by xiaooloong** [comment]
我的 943602CS 也遇到过这个问题，加入 `AirportBrcmFixup.kext` 后正常了。
