### ISSUE TITLE
新主板，BIOS版本4.4，雷电接口不工作啊

### ISSUE THREAD

**Issue by bibugo** [fangf2018/ASRock-Z390-Phantom-ITX-OpenCore-Hackintosh#16]
新买的主板，BIOS版本4.4。
雷电口插着设备启动，hackintool能看到usb和雷电控制器XHC和XHC2，但不能识别usb设备，拔出再插入也没反应，能给iphone充电。
如果不插入设备启动，hackintool只能看到usb控制器XHC，没有XHC2，插拔雷电口，除了可充电，没反应。

高手能不能提示一下该怎么解决啊？

**Comment by wxunyang** [comment]
TB的USB兼容功能要在主板开启才可以吧，不然只能插显示器这些用。
确实是需要插线启动，不然找不到设备。

**Comment by linseedoil** [comment]
> TB的USB兼容功能要在主板开启才可以吧，不然只能插显示器这些用。
> 确实是需要插线启动，不然找不到设备。

所以现在type c口还是无法实现热插拔？还是必须要插着启动才可以？我自己测试是这样的
