### ISSUE TITLE
关于睡眠唤醒和vault登录的问题

### ISSUE THREAD

**Issue by desert0616** [fangf2018/ASRock-Z390-Phantom-ITX-OpenCore-Hackintosh#2]
你好，多谢分享！

在大体上使用了你分享的文件后，我的10.14.6基本上完美使用并且可以顺利升级到10.15。

现在我遇到了两个问题，

1. 睡眠后无法通过usb或者蓝牙键鼠唤醒，似乎没有任何反应。可以通过点击开关键正常唤醒。
2. 在opencore那个123的界面，以及后来的vault登录界面，蓝牙键盘工作不正常。症状是只要按下键盘上的某个键子触发键盘与蓝牙进行配对，就会不停的触发按键（在密码栏打出一堆字符）。

我使用的网卡是cs2，跟你的2cs不同。我想请问你使用vault么，是否对你的2cs有什么特别的配置以至于可能这些配置在cs2下有问题？

3. 对于BIOS配置，如果你没有提到，是否就意味着他们是出于主板的default状态？

谢谢！

**Comment by GeekAudio** [comment]
=
