### ISSUE TITLE
大佬  我现在用的clover  能直接转oc吗？需要重装吗还是？

### ISSUE THREAD

**Issue by jy2miku** [fangf2018/ASRock-Z390-Phantom-ITX-OpenCore-Hackintosh#23]

**Comment by jyk1987** [comment]
不用重装。你只是换个引导啊。你可以先把引导放u盘上，可以正常启动了。再放到硬盘的efi分区。

**Comment by jy2miku** [comment]
> 不用重装。你只是换个引导啊。你可以先把引导放u盘上，可以正常启动了。再放到硬盘的efi分区。
大佬  我用这个oc开机了  但是显卡型号不对  我是5700  并且雷电啥的也不能用  是要升级bios吗

**Comment by jyk1987** [comment]
这个东西不是我弄的。我也只是帮忙回答个问题。
我是rx590，使用正常。至于雷电，我还没有用过。
