### ISSUE TITLE
能否贴一下bios的配置。

### ISSUE THREAD

**Issue by Easy-Ez** [fangf2018/ASRock-Z390-Phantom-ITX-OpenCore-Hackintosh#28]
为了抄作业跟你搞了套一样的配置， 能否贴一下bios配置呢
另外BrcmPatchRAM3中的是蓝牙驱动吗，也许放入对应文件夹中吗。 
谢谢

**Comment by xiaooloong** [comment]
`BrcmPatchRAM3` 里面是非白果拆机卡的驱动，例如 dw1560 这些卡。

**Comment by Easy-Ez** [comment]
@xiaooloong  感谢
顺便说一下 bios 在readme最后面，贴一下，方便跟我一样瞎的人， 哈哈
Advanced \ Chipset Configuration → Vt-d : Disabled

Advanced \ Super IO Configuration → Serial Port: Disabled

Advanced \ USB Configuration → XHCI Hand-off : Enabled

Advanced \ Chipset Configuration → Share Memory : 128MB

Advanced \ Chipset Configuration → IGPU Multi-Monitor : Enabled
