### ISSUE TITLE
Reset nvram option missing on bootscreen

### ISSUE THREAD

**Issue by krwt** [fangf2018/ASRock-Z390-Phantom-ITX-OpenCore-Hackintosh#32]
After using the new one, reset nvram option on opencanopy is missing.  AllowNvramReset is already set to true. Anyone else noticed this?

**Comment by cunc** [comment]
Maybe you can try the space bar on the boot screen.
Or disable the Misc - Boot - HideAuxiliary

**Comment by krwt** [comment]
> Or disable the Misc - Boot - HideAuxiliary

This fixed it, thank you!!
