### ISSUE TITLE
Thunderbolt 3 planned?

### ISSUE THREAD

**Issue by kleuter** [fangf2018/ASRock-Z390-Phantom-ITX-OpenCore-Hackintosh#4]
Please don't close it but rather mark as feature request, please

**Comment by GeekAudio** [comment]
雷电3的驱动一直在搞，精力以及能力实在有限。我这里提供教程您可以邀请其他开发者深入研究一下
 https://github.com/al3xtjames/ThunderboltPkg
感谢您
