### ISSUE TITLE
Takes forever to boot, stuck at 100%?

### ISSUE THREAD

**Issue by jwmann** [fangf2018/ASRock-Z390-Phantom-ITX-OpenCore-Hackintosh#9]
I already have a working Clover setup but I wanted to try this one out.

I threw the EFI onto a USB key and booted my Hackintosh drive using the new OpenCore bootloader (not a very nice looking bootloader mind you)

It started to boot via the apple logo and I've waited maybe 30-40 minutes as it slowly booted.
The progress bar is now at 100% and nothing happens.

Is there like a verbose mode in this?
Maybe something is happening and I can't see it?

**Comment by GeekAudio** [comment]
smbios!
PlatformInfo-Generic

**Comment by carlosxfigueroa** [comment]
patch your own usbX and make sure haltlevel is set with integer not real

**Comment by carlosxfigueroa** [comment]
> smbios!
> PlatformInfo-Generic

any chance you can help with nvram and setting your boot drive between windows and mac os
